import base64
import io
import os
import re
import time
from typing import Annotated, Literal

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

from AgentNodes.LLMNode import LLMNode
from config import DEBUG

MAX_DEBUG_ITER = 5


# SubGraph State for Plotting Division
class PlotState_CSV(TypedDict):
    """Represents the state of the `Plotter` agent."""

    error: str
    plot_code: str
    refinement_iter: int
    csv_schema: str  #!CANNOT BE EMPTY
    goal: str  #!CANNOT BE EMPTY
    refined_prompt: str
    pandas_dump: pd.DataFrame

    # output
    image_base64: str


class PlotAgent_CSV:
    """
    Creates an instance of a plotting agent.

    The `PlotAgent` accepts inputs as a dictionary with kwargs:
        {goal, schema}
    """

    if DEBUG:
        start_time = 0

    def __init__(self, model, refine=True):
        self._refine = refine
        self._graph = self._init_graph(model)

    def get_graph(self):
        """Get a runnable instance of the plotter chain."""
        return self._graph

    def _init_graph(self, model):
        graph_builder = StateGraph(PlotState_CSV)
        graph_builder.add_node("initialize", init_state)
        graph_builder.add_node("executor", executor_node)
        graph_builder.add_node("generator", PlotGeneratorNode(model, "PLOT_GEN"))
        graph_builder.add_node("cleanup", cleanup)
        graph_builder.add_edge(START, "initialize")
        graph_builder.add_edge("generator", "executor")
        graph_builder.add_conditional_edges(
            "executor", eval_plot, {"pass": "cleanup", "failed": "generator"}
        )
        graph_builder.add_edge("cleanup", END)

        if self._refine:
            graph_builder.add_edge("initialize", "prompt_refiner")
            graph_builder.add_node("prompt_refiner", RefinerNode(model))
            graph_builder.add_edge("prompt_refiner", "generator")
        else:
            graph_builder.add_edge("initialize", "generator")

        return graph_builder.compile()


def init_state(state: PlotState_CSV):
    """Enforces correct input format, and
    initialize the graph state."""

    PlotAgent_CSV.start_time = time.time()

    valid = len(state["goal"]) > 0 and len(state["csv_schema"]) > 0

    if not valid:
        raise ValueError("Input to the plot generator should not be empty!")

    # Initialize state
    return {
        "refinement_iter": 0,
        "error": "",
        "plot_code": "",
        "refined_prompt": state["goal"],
    }


# Graph Nodes
def executor_node(state: PlotState_CSV):
    """
    Executes the code that was generated by the Generator

    Mutates:
        - Update error messages that results if a runtime error
          occurs from the provided dataset.
    """

    err = ""
    img_base64 = ""
    exec_code = state["plot_code"]
    exec_code += "\n"

    exec_globals = {"plt": plt}
    exec_locals = {}
    start_time = time.time()

    try:

        exec(exec_code, exec_globals, exec_locals)

        generate_fig = exec_locals["generate_fig"]
        fig = generate_fig(state["pandas_dump"])
        buf = io.BytesIO()
        fig.savefig(buf, format="png")
        plt.close()

        buf.seek(0)
        img_base64 = base64.b64encode(buf.read()).decode("utf-8")

    except Exception as e:
        err = f"Error: {e}"

    if DEBUG:
        print(f"[PLOT_EXEC] Time elapsed: {time.time() - start_time} s")

    return {
        "error": err,
        "refinement_iter": state["refinement_iter"] + 1,
        "image_base64": img_base64,
    }


def eval_plot(state: PlotState_CSV) -> Literal["pass", "failed"]:
    """
    Evaluates a plot based after a call from `exec_plot`.
    Returns whether execution was successful or not
    under the maximum number of iterations.
    """
    passed = state["refinement_iter"] >= MAX_DEBUG_ITER or len(state["error"]) == 0
    return "pass" if passed else "failed"


def cleanup(state: PlotState_CSV):
    """Cleans up any temporary files that was used."""
    if DEBUG:
        print(
            f"TIME ELAPSED IN PLOTTING: {time.time() - PlotAgent_CSV.start_time} (in plot_agent_csv)"
        )
    return


class PlotGeneratorNode(LLMNode):
    """A node that generates python code to generate a plot"""

    SYSTEM_TEMPLATE = """You are a python programmer tasked to wite python code to generate
    vizualizations using matplotlib. Generate a runnable code that follows user's guidelines 
    the most.

    You should define your function 'generate_fig(df)' which takes a pandas dataframe object, 
    which returns a matplotlib fig object.
    ONLY WRITE FOR THE FUNCTION DEFINITION ONLY. For the plotting library, use matplotlib.

    Additionally, should the user point out an error in the code, you should address
    these errors as correctly as you can.

    Try to include numerical labels into your plot to make it more informative.
    Also, fill out the X and Y axis labels if nessecary. 

    **For the labels, you should always write them in INDONESIAN**

    You will work with
    the following schema for the data represented by a list:
    "{csv_schema}"

    Respond in python code only, and DO NOT generate code that will change the contents
    of the csv file.

    """

    USER_TEMPLATE = """{refined_prompt}
    Below is the code you will work with, please make nessecary changes to the code:
    {plot_code}
    Also below is the error summary from running the code:
    {error} """

    def __init__(self, model, name=None):
        super().__init__(model, self.SYSTEM_TEMPLATE, self.USER_TEMPLATE, name)

    def update_state(self, state) -> dict:
        code = clean_code(self.invoke_llm(state).content)
        return {"plot_code": code}


class RefinerNode(LLMNode):
    """A node that refines user query to generate
    a list of specific instructions for the
    code generator to follow."""

    SYSTEM_TEMPLATE = """You are a data analyst tasked with generating concrete steps to visualize
    data based on the given query by the user. Specify an appropriate data
    visualization technique and lay out the steps and function calls to visualize
    the data. You must specify these steps with plain English, using helper function
    and variable names as nessecary.

    You will work with
    the following schema for the data represented by a list:
    "{csv_schema}" 

    For the csv schema, take the column names AS GRANTED and do not change the names
    while describing the steps.

    Remember to rewrite the original question as your answer!"""

    USER_TEMPLATE = """{goal}"""

    def __init__(self, model):
        super().__init__(model, self.SYSTEM_TEMPLATE, self.USER_TEMPLATE)

    def update_state(self, state) -> dict:
        refined_prompt = self.invoke_llm(state)
        return {"refined_prompt": refined_prompt}


####################################################################################################


def clean_code(raw_code: str):
    """Clean up code generated by an LLM"""
    pattern = re.compile(r"```python\s*([\s\S]+?)\s*```", re.MULTILINE)
    code_blocks = pattern.findall(raw_code)
    code_blocks_combined = "\n".join(code_blocks)
    return code_blocks_combined
